export const topicSeo = [
  ['B1-T01', 'Derechos, deberes y funciones de la Corona', 'cómo se articulan la Corona, las Cortes Generales y la figura del Rey en la Constitución', 'corona-constitucion-tai'],
  ['B1-T02', 'Cortes Generales, Tribunal Constitucional y Defensor del Pueblo', 'competencias de los órganos del Estado y mecanismos de defensa de la Constitución', 'cortes-tribunal-constitucional-defensor'],
  ['B1-T03', 'Composición y funciones del Gobierno', 'estructura del Gobierno, el Presidente y sus facultades', 'gobierno-estructura-funciones'],
  ['B1-T04', 'TREBEP, transparencia y Agenda 2030', 'régimen de los empleados públicos, transparencia y Agenda 2030', 'trebep-transparencia-agenda-2030'],
  ['B1-T05', 'Igualdad, LGTBI, discapacidad y dependencia', 'igualdad, diversidad y atención a personas con discapacidad o dependencia', 'igualdad-no-discriminacion-lgtbi'],
  ['B1-T06', 'Identidad, firma electrónica y Agenda Digital', 'identidad y firma electrónicas, INEE y Agenda Digital España', 'firma-electronica-identidad-digital'],
  ['B1-T07', 'Protección de datos y derechos digitales', 'RGPD, LOPDGDD y derechos digitales de la ciudadanía', 'rgpd-proteccion-datos-derechos-digitales'],
  ['B1-T08', 'Procedimiento electrónico, ENS e interoperabilidad', 'sedes, expediente electrónico, ENS e interoperabilidad', 'procedimiento-electronico-ens-interoperabilidad'],
  ['B1-T09', 'Sedes electrónicas, Cl@ve y servicios comunes', 'sede electrónica, Carpeta Ciudadana, Cl@ve y servicios comunes', 'sede-electronica-clave-servicios-comunes'],
  ['B2-T01', 'Representación de la información y arquitectura', 'sistemas de numeración, lógica booleana y arquitectura de von Neumann', 'arquitectura-ordenadores-representacion'],
  ['B2-T02', 'Periféricos, conectividad e impresión', 'periféricos, memoria, buses, dispositivos de entrada y salida e impresión', 'perifericos-conectividad-impresion'],
  ['B2-T03', 'Algoritmos, estructuras de datos y ficheros', 'algoritmos, arrays, pilas, colas, árboles, grafos y ficheros', 'algoritmos-estructuras-datos-ficheros'],
  ['B2-T04', 'Windows, Unix, Linux y sistemas móviles', 'familias de sistemas operativos, estructura, líneas de órdenes y seguridad', 'sistemas-operativos-windows-linux'],
  ['B2-T05', 'Bases de datos relacionales, objetos y NoSQL', 'modelo relacional, álgebra relacional, ACID y bases NoSQL', 'bases-datos-nosql-transacciones'],
  ['B3-T01', 'Modelo ER, diseño y normalización', 'entidades, relaciones, atributos, claves y formas normales', 'modelo-er-normalizacion-diseno-bases-datos'],
  ['B3-T02', 'Programación, tipos, bucles y funciones', 'tipos de datos, operadores, estructuras de control y funciones', 'programacion-tipos-bucles-funciones'],
  ['B3-T03', 'SQL, consultas, procedimientos y disparadores', 'DDL, DML, consultas, procedimientos, disparadores y seguridad', 'sql-consultas-procedimientos-triggers'],
  ['B3-T04', 'POO, patrones de diseño y UML', 'herencia, polimorfismo, patrones de diseño y diagramas UML', 'programacion-orientada-objetos-uml-patrones'],
  ['B3-T05', 'Jakarta EE, .NET, persistencia e interfaces', 'Jakarta EE, ASP.NET, Entity Framework y ADO.NET', 'jakarta-ee-net-persistencia'],
  ['B3-T06', 'Capas, MVC, APIs y servicios web', 'arquitectura por capas, MVC, APIs REST y servicios web', 'arquitectura-capas-mvc-rest'],
  ['B3-T07', 'HTML, XML, CSS, JavaScript y navegadores', 'lenguajes web, DOM, eventos, motores y renderizado', 'html-xml-css-javascript-web'],
  ['B3-T08', 'Accesibilidad, usabilidad y seguridad', 'WCAG, usabilidad, XSS, CSRF, CSP y ataques de inyección', 'accesibilidad-wcag-usabilidad-seguridad'],
  ['B3-T09', 'Repositorios, pruebas, Git y CI/CD', 'control de versiones, pruebas unitarias, documentación e integración continua', 'git-pruebas-control-versiones'],
  ['B4-T01', 'Administración de Windows y Linux', 'usuarios, permisos, procesos, servicios, SAM y sistemas de ficheros', 'administracion-windows-linux'],
  ['B4-T02', 'Backup, RAID, virtualización y recuperación', 'RAID, copias de seguridad, máquinas virtuales y recuperación ante desastres', 'backup-raid-virtualizacion'],
  ['B4-T03', 'Correo, contenedores y microservicios', 'SMTP, IMAP, POP3, MIME, contenedores y microservicios', 'smtp-imap-contenedores'],
  ['B4-T04', 'Redes locales, VLAN y monitorización', 'topologías, Ethernet, VLAN, herramientas y monitorización', 'redes-locales-vlan-monitorizacion'],
  ['B4-T05', 'Seguridad, criptografía, CPD e incidencias', 'criptografía, CPD, activos de seguridad y gestión de incidencias', 'seguridad-criptografia-cpd-incidentes'],
  ['B4-T06', 'Transmisión, switching, wireless y móvil', 'medios de transmisión, switches, puntos de acceso, WiFi y redes móviles', 'redes-transmision-wireless-movil'],
  ['B4-T07', 'Modelo OSI, TCP/IP, ARP e ICMP', 'capas del modelo OSI, TCP/IP, ARP, ICMP, NAT y DNS', 'osi-tcpip-arp-icmp'],
  ['B4-T08', 'Internet, DNS, HTTP, HTTPS y TLS', 'historia de Internet, DNS, HTTP, HTTPS, FTP, SSH y TLS/SSL', 'internet-dns-http-https-tls'],
  ['B4-T09', 'Cortafuegos, VPN y seguridad perimetral', 'cortafuegos, VPN, IDS/IPS, honeypots, PPTP, L2TP, IPsec y SSH', 'cortafuegos-vpn-seguridad-perimetral'],
  ['B4-T10', 'Topologías, Ethernet y dispositivos de red', 'topologías, Ethernet, switching, puntos de acceso y dispositivos de red', 'topologias-ethernet-conmutadores'],
]
